_BASE_: "Base-MSBC-Net.yaml"
MODEL:
  WEIGHTS: "torchvision-R-101.pkl"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
  MSBCNet:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 2
DATASETS:
#  TRAIN: ("coco_2017_train",)
#  TEST:  ("coco_2017_val",)
  TRAIN: ("rectal_tumor_train",)
  TEST:  ("rectal_tumor_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
